[package]
name = "smfr"
version = "0.1.0"
authors = ["tinaxd <tinaxd@tinax.work>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
